export type AppointmentResponseDTO = {
  id: string;
  barberId: string;
  clientId?: string;
  clientName: string;
  clientLastname: string;
  clientPhone?: string;
  clientEmail?: string;
  serviceId: string;
  serviceName: string;
  servicePrice: number;
  serviceDuration: number;
  date: string;
  startTime: string;
  endTime: string;
  status: string;
  cancelReason?: string;
  cancelledAt?: Date | null;
  statusHistory: Array<{ status: string; timestamp: Date; actor: string }>;
  createdAt: Date;
  updatedAt: Date;
};
